name: Build and Push Docker Image

on:
  push:
    tags:
      - prod-*

jobs:
  build-and-push-to-prod:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: clone the deployment scripts repository
        uses: actions/checkout@v2
        with:
          repository: EatNourisha/infrastructure
          token: ${{ secrets.INFRASTRUCTURE_GITHUB_ACCESS_TOKEN }}
          ref: main

      - name: update image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = "${{ github.sha }}"' 'helm-charts/apps/eatnourisha-backend/prod.values.yaml'

      - name: commit changes to image tag
        run: |
          git config user.email "${{ github.event.sender.email }}"
          git config user.name "${{ github.event.sender.login }}"
          git add helm-charts/apps/eatnourisha-backend/prod.values.yaml
          git commit -m "update image tag to ${{ github.sha }}" ||  echo "No changes to commit"
          git remote -v
          git push
