name: Build and Push Docker Image

on:
  push:
    tags:
      - stage-*
    branches:
      - develop

jobs:
  build-and-push-to-stage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and tag the Docker image
        run: docker build .
          --tag registry.digitalocean.com/eatnourisha/eatnourisha-backend:${{ github.sha }}
          --tag registry.digitalocean.com/eatnourisha/eatnourisha-backend:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 900

      - name: Push the tagged Docker image
        run: |
          docker push registry.digitalocean.com/eatnourisha/eatnourisha-backend:${{ github.sha }}
          docker push registry.digitalocean.com/eatnourisha/eatnourisha-backend:latest

      - name: clone the deployment scripts repository
        uses: actions/checkout@v2
        with:
          repository: EatNourisha/infrastructure
          token: ${{ secrets.INFRASTRUCTURE_GITHUB_ACCESS_TOKEN }}
          ref: main

      - name: update image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = "${{ github.sha }}"' 'helm-charts/apps/eatnourisha-backend/stage.values.yaml'

      - name: commit changes to image tag
        run: |
          git config user.email "${{ github.event.sender.email }}"
          git config user.name "${{ github.event.sender.login }}"
          git add helm-charts/apps/eatnourisha-backend/stage.values.yaml
          git commit -m "update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git remote -v
          git push
